/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.zoolomania.funcional.vista;

import com.zoolomania.funcional.control.ContinenteTrs;
import com.zoolomania.funcional.control.EspecieTrs;
import com.zoolomania.funcional.control.HabitatTrs;
import com.zoolomania.funcional.control.MyExcepcion;
import com.zoolomania.funcional.control.UtilGestion;
import com.zoolomania.funcional.modelo.Continente;
import com.zoolomania.funcional.modelo.Especie;
import com.zoolomania.funcional.modelo.Habitat;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Erick Díaz
 */
public class frmHabitat extends javax.swing.JFrame {

    HabitatTrs htrs = new HabitatTrs();
    EspecieTrs etrs = new EspecieTrs();
    ContinenteTrs ctrs = new ContinenteTrs();
    List<Habitat> habitats = htrs.listar();
    List<Especie> especies = etrs.listar();
    List<Continente> continentes = ctrs.listar();
    boolean bandera = false;

    public void cargarTablaE() {
        Object[] columna = {"Marca", "Especie", "Nombre Científico", "Descripción"};
        DefaultTableModel modeloE = new DefaultTableModel(columna, 0);
        for (Especie e : especies) {
            short marca = e.getMarca();
            String especie = e.getNombreEspecie();
            String nombreC = e.getNombreCientifico();
            String descripcion = e.getDescripcion();
            Object[] fila = {marca, especie, nombreC, descripcion};
            modeloE.addRow(fila);
        }
        this.tablaE.setModel(modeloE);
    }

    private void cargarTablaH() {
        Object[] columna = {"ID", "Habitat", "Clima", "Vegetación"};
        DefaultTableModel modeloH = new DefaultTableModel(columna, 0);
        for (Habitat h : habitats) {
            short id = h.getId();
            String nombreH = h.getNombreHabitat();
            String clima = h.getClima();
            String vegetacion = h.getVegetacion();
            Object[] fila = {id, nombreH, clima, vegetacion};
            modeloH.addRow(fila);
        }
        this.tablaH.setModel(modeloH);
    }

    private void cargarTablaC() {
        Object[] columna = {"ID", "Continente"};
        DefaultTableModel modeloC = new DefaultTableModel(columna, 0);
        for (Continente c : continentes) {
            short id = c.getId();
            String continente = c.getNombreContienete();
            Object[] fila = {id, continente};
            modeloC.addRow(fila);
        }
        this.tablaC.setModel(modeloC);
    }

    /**
     * Creates new form frmHabitat
     */
    public frmHabitat() {
        initComponents();
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel6, "src/iconos/logo.jpg");
        setLocationRelativeTo(null);
        cargarTablaE();
        cargarTablaH();
        cargarTablaC();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        bRegresar = new javax.swing.JButton();
        bVerTodoO = new javax.swing.JButton();
        bEliminarO = new javax.swing.JButton();
        bAgregarO = new javax.swing.JButton();
        bOrdenarO = new javax.swing.JButton();
        cBoxO = new javax.swing.JComboBox<>();
        rDescendenteO = new javax.swing.JRadioButton();
        rAscendenteO = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaH = new javax.swing.JTable();
        cBox = new javax.swing.JComboBox<>();
        rDescendente = new javax.swing.JRadioButton();
        rAscendente = new javax.swing.JRadioButton();
        bOrdenar = new javax.swing.JButton();
        bRelaciones = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        bActualizar = new javax.swing.JButton();
        bAgregar = new javax.swing.JButton();
        jVegetacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jClima = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaE = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaC = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        bRegresar.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        bRegresar.setText("Menu Principal");
        bRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegresarActionPerformed(evt);
            }
        });

        bVerTodoO.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        bVerTodoO.setText("Ver Todo");
        bVerTodoO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVerTodoOActionPerformed(evt);
            }
        });

        bEliminarO.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        bEliminarO.setText("Eliminar");
        bEliminarO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarOActionPerformed(evt);
            }
        });

        bAgregarO.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        bAgregarO.setText("Agregar");
        bAgregarO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarOActionPerformed(evt);
            }
        });

        bOrdenarO.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        bOrdenarO.setText("Ordenar");
        bOrdenarO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOrdenarOActionPerformed(evt);
            }
        });

        cBoxO.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        cBoxO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "ID" }));

        buttonGroup2.add(rDescendenteO);
        rDescendenteO.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        rDescendenteO.setText("Descendente");

        buttonGroup2.add(rAscendenteO);
        rAscendenteO.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        rAscendenteO.setSelected(true);
        rAscendenteO.setText("Ascendente");

        tablaH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaH);

        cBox.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        cBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "ID" }));

        buttonGroup1.add(rDescendente);
        rDescendente.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        rDescendente.setText("Descendente");

        buttonGroup1.add(rAscendente);
        rAscendente.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        rAscendente.setSelected(true);
        rAscendente.setText("Ascendente");

        bOrdenar.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        bOrdenar.setText("Ordenar");
        bOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOrdenarActionPerformed(evt);
            }
        });

        bRelaciones.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        bRelaciones.setText("Ver relaciones");
        bRelaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRelacionesActionPerformed(evt);
            }
        });

        bEliminar.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        bActualizar.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        bActualizar.setText("Actualizar");
        bActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarActionPerformed(evt);
            }
        });

        bAgregar.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        bAgregar.setText("Agregar");
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });

        jVegetacion.setBackground(new java.awt.Color(0, 102, 153));
        jVegetacion.setForeground(new java.awt.Color(255, 255, 255));
        jVegetacion.setBorder(null);

        jLabel4.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        jLabel4.setText("Vegetación:");

        jClima.setBackground(new java.awt.Color(0, 102, 153));
        jClima.setForeground(new java.awt.Color(255, 255, 255));
        jClima.setBorder(null);

        jLabel3.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        jLabel3.setText("Clima:");

        jNombre.setBackground(new java.awt.Color(0, 102, 153));
        jNombre.setForeground(new java.awt.Color(255, 255, 255));
        jNombre.setBorder(null);

        jLabel2.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        jLabel2.setText("Nombre/Habitat:");

        jid.setBackground(new java.awt.Color(0, 102, 153));
        jid.setForeground(new java.awt.Color(255, 255, 255));
        jid.setBorder(null);

        jLabel1.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        jLabel1.setText("ID:");

        jLabel6.setText("jLabel6");

        tablaE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tablaE);

        jTabbedPane1.addTab("Especies", jScrollPane3);

        tablaC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tablaC);

        jTabbedPane1.addTab("Continentes", jScrollPane4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(bOrdenar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cBox, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rAscendente, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rDescendente, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jVegetacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jClima, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jid, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(bActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30)
                                .addComponent(bRelaciones))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)
                        .addComponent(bRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(bOrdenarO)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cBoxO, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bAgregarO))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rDescendenteO)
                            .addComponent(bEliminarO))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bVerTodoO)
                            .addComponent(rAscendenteO, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bAgregar)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jVegetacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(1, 1, 1)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(2, 2, 2)
                                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jClima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(bActualizar)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator4)
                                        .addGap(31, 31, 31))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(bEliminar)
                                            .addComponent(bRelaciones))
                                        .addGap(52, 52, 52))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 6, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bRegresar))
                                .addGap(100, 100, 100)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bOrdenar)
                            .addComponent(cBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rAscendente)
                            .addComponent(bOrdenarO)
                            .addComponent(cBoxO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rDescendenteO)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(rDescendente))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rAscendenteO, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(bAgregarO)
                                            .addComponent(bEliminarO)
                                            .addComponent(bVerTodoO))
                                        .addGap(63, 63, 63)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
        // TODO add your handling code here:
        if (!(jNombre.getText().isEmpty() | jVegetacion.getText().isEmpty()
                | jClima.getText().isEmpty() | jid.getText().isEmpty())) {
            try {
                htrs.guardar(new Habitat(jNombre.getText(), jClima.getText(), jVegetacion.getText(),
                        Short.parseShort(jid.getText())));
                jNombre.setText("");
                jClima.setText("");
                jVegetacion.setText("");
            } catch (NumberFormatException n) {
                JOptionPane.showMessageDialog(null, "Por favor ingrese número enteros para los campos cuantitativos",
                        "Error en la capa 8", JOptionPane.INFORMATION_MESSAGE);
            } catch (MyExcepcion ex) {
                Logger.getLogger(frmHabitat.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                jid.setText("");
                cargarTablaH();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe de llenar todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bAgregarActionPerformed

    private void bActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarActionPerformed
        // TODO add your handling code here:
        if (!(jNombre.getText().isEmpty() | jVegetacion.getText().isEmpty()
                | jClima.getText().isEmpty()) & tablaH.getSelectedRow() > -1) {
            JOptionPane.showMessageDialog(null, "El ID no se puede modificar", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            try {
                htrs.actulizar(new Habitat(jNombre.getText(), jClima.getText(), jVegetacion.getText(),
                        habitats.get(tablaH.getSelectedRow()).getId()));
                jNombre.setText("");
                jClima.setText("");
                jVegetacion.setText("");
            } catch (MyExcepcion ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Error al Actualizar", JOptionPane.ERROR_MESSAGE);
            } finally {
                jid.setText("");
                cargarTablaH();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor seleccione una fila a eliminar "
                    + "o compuebe que los campos estén llenos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bActualizarActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        // TODO add your handling code here:
        if (tablaH.getSelectedRow() > -1) {
            try {
                UtilGestion.eliminacionCompleta(habitats.get(tablaH.getSelectedRow()));
                htrs.eliminar(habitats.get(tablaH.getSelectedRow()));
            } catch (MyExcepcion ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Error al Guardar", JOptionPane.ERROR_MESSAGE);
            } finally {
                habitats = htrs.listar();
                continentes = ctrs.listar();
                cargarTablaC();
                cargarTablaE();
                cargarTablaH();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor seleccione una fila a eliminar", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bEliminarActionPerformed

    private void bRelacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRelacionesActionPerformed
        // TODO add your handling code here:
        if (tablaH.getSelectedRow() > -1) {
            especies = habitats.get(tablaH.getSelectedRow()).getEspecies();
            cargarTablaE();
            bandera = true;
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione la fila a la que quiere ver sus Especies", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bRelacionesActionPerformed

    private void bOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOrdenarActionPerformed
        // TODO add your handling code here:
        if (cBox.getSelectedIndex() == 0) {
            Habitat.bandera = false;
            if (rAscendente.isEnabled()) {
                Collections.sort(habitats, Collections.reverseOrder());
            } else if (rDescendente.isEnabled()) {
                Collections.sort(habitats);
            }
        } else if (cBox.getSelectedIndex() == 1) {
            Habitat.bandera = true;
            if (rAscendente.isEnabled()) {
                Collections.sort(habitats);
            } else if (rDescendente.isEnabled()) {
                Collections.sort(habitats, Collections.reverseOrder());
            }
        }
        cargarTablaH();
    }//GEN-LAST:event_bOrdenarActionPerformed

    private void bOrdenarOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOrdenarOActionPerformed
        // TODO add your handling code here:
        if (cBoxO.getSelectedIndex() == 0) {
            Especie.bandera = false;
            if (rAscendenteO.isEnabled()) {
                Collections.sort(especies, Collections.reverseOrder());
                Collections.sort(continentes, (o1, o2) -> {
                    return o2.getNombreContienete().compareToIgnoreCase(o1.getNombreContienete());
                });
            } else if (rDescendenteO.isEnabled()) {
                Collections.sort(especies);
                Collections.sort(continentes, (o1, o2) -> {
                    return o1.getNombreContienete().compareToIgnoreCase(o2.getNombreContienete());
                });
            }
        } else if (cBoxO.getSelectedIndex() == 1) {
            Especie.bandera = true;
            if (rAscendenteO.isEnabled()) {
                Collections.sort(especies, Collections.reverseOrder());
                Collections.sort(continentes, (o1, o2) -> {
                    return Short.compare(o2.getId(), o1.getId());
                });
            } else if (rDescendenteO.isEnabled()) {
                Collections.sort(especies);
                Collections.sort(continentes, (o1, o2) -> {
                    return Short.compare(o1.getId(), o2.getId());
                });
            }
        }
        cargarTablaE();
        cargarTablaC();
    }//GEN-LAST:event_bOrdenarOActionPerformed

    private void bAgregarOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarOActionPerformed
        // TODO add your handling code here:
        if (tablaH.getSelectedRow() > -1 & tablaE.getSelectedRow() > -1 & !bandera) {
            Habitat habitat = habitats.get(tablaH.getSelectedRow());
            Especie especie = especies.get(tablaE.getSelectedRow());
            if (!habitat.getEspecies().contains(especie)) {
                habitat.agregarEspecie(especie);
                especie.agregarHabitat(habitat);
                try {
                    htrs.actulizar(habitat);
                    etrs.actulizar(especie);
                    JOptionPane.showMessageDialog(null, "Se a agregado especie al Habitat", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                } catch (MyExcepcion ex) {
                    Logger.getLogger(frmHabitat.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "No se puede agregar la especie pues ya está dentro de la lista.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else if (tablaH.getSelectedRow() > -1 & tablaC.getSelectedRow() > -1 & !bandera) {
            Habitat habitat = habitats.get(tablaH.getSelectedRow());
            Continente continente = continentes.get(tablaC.getSelectedRow());
            if (!habitat.getContinentes().contains(continente)) {
                habitat.agregarContinente(continente);
                continente.agregarHabitat(habitat);
                try {
                    htrs.actulizar(habitat);
                    ctrs.actulizar(continente);
                    JOptionPane.showMessageDialog(null, "Se a agregado continente al Habitat", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                } catch (MyExcepcion ex) {
                    Logger.getLogger(frmHabitat.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "No se puede agregar el continente pues ya está dentro de la lista.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe de seleccionar una fila a agregar la relación, o salga de las relaciones del Habitat",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bAgregarOActionPerformed

    private void bEliminarOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarOActionPerformed
        // TODO add your handling code here:
        if (tablaH.getSelectedRow() > -1 & tablaE.getSelectedRow() > -1 & bandera) {
            Habitat habitat = habitats.get(tablaH.getSelectedRow());
            Especie especie = especies.get(tablaE.getSelectedRow());
            if (habitat.getEspecies().contains(especie)) {
                habitat.eliminarEspecie(especie);
                especie.elimninarHabitat(habitat);
                try {
                    htrs.actulizar(habitat);
                    etrs.actulizar(especie);
                    JOptionPane.showMessageDialog(null, "Especie Eliminada del Habitat", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                } catch (MyExcepcion ex) {
                    Logger.getLogger(frmHabitat.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    cargarTablaE();
                }
            } else {
                JOptionPane.showMessageDialog(null, "No se puede eliminar la especie pues no está dentro de la lista.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else if (tablaH.getSelectedRow() > -1 & tablaC.getSelectedRow() > -1 & bandera) {
            Habitat habitat = habitats.get(tablaH.getSelectedRow());
            Continente continente = continentes.get(tablaC.getSelectedRow());
            if (habitat.getContinentes().contains(continente)) {
                habitat.eliminarContinente(continente);
                continente.eliminarHabitat(habitat);
                try {
                    htrs.actulizar(habitat);
                    ctrs.actulizar(continente);
                    JOptionPane.showMessageDialog(null, "Continente Eliminado del Habitat", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                } catch (MyExcepcion ex) {
                    Logger.getLogger(frmHabitat.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    cargarTablaC();
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila del habitat a la cual desea agregarle la especie. O ingrese a las relaciones del Habitat",
                    "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_bEliminarOActionPerformed

    private void bVerTodoOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVerTodoOActionPerformed
        // TODO add your handling code here:
        especies = etrs.listar();
        habitats = htrs.listar();
        continentes = ctrs.listar();
        cargarTablaE();
        cargarTablaC();
        bandera = false;
    }//GEN-LAST:event_bVerTodoOActionPerformed

    private void bRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegresarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new frmMenuPrincipal().setVisible(true);
    }//GEN-LAST:event_bRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHabitat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHabitat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHabitat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHabitat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHabitat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualizar;
    private javax.swing.JButton bAgregar;
    private javax.swing.JButton bAgregarO;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bEliminarO;
    private javax.swing.JButton bOrdenar;
    private javax.swing.JButton bOrdenarO;
    private javax.swing.JButton bRegresar;
    private javax.swing.JButton bRelaciones;
    private javax.swing.JButton bVerTodoO;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cBox;
    private javax.swing.JComboBox<String> cBoxO;
    private javax.swing.JTextField jClima;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jVegetacion;
    private javax.swing.JTextField jid;
    private javax.swing.JRadioButton rAscendente;
    private javax.swing.JRadioButton rAscendenteO;
    private javax.swing.JRadioButton rDescendente;
    private javax.swing.JRadioButton rDescendenteO;
    private javax.swing.JTable tablaC;
    private javax.swing.JTable tablaE;
    private javax.swing.JTable tablaH;
    // End of variables declaration//GEN-END:variables
}
